### ISSUE TITLE
Build sponsor logo grid

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#10]
Views block that will be referenced by the Reference - Block paragraph type.

Design for reference: https://projects.invisionapp.com/share/XJE4W9E86#/screens/272188623

**Comment by jnettik** [comment]
This view block exists along with a draggable view to manually sort sponsors. The sorting might be a little awkward due to D8 Draggable Views not supporting sorting within groupings. So for now there's two levels of sorting:

- Teir (taxonomy) weight
- Draggable views weight

Hopefully this makes sense. Ping me if it doesn't.

**Comment by nswitzer** [comment]
Thanks @jnettik. This looks good to me. Closing
